Keep 138/support invoke script in sign transaction package
wavesplatform/waves-keeper pull request #153
Opened 2021-11-19 10:10 UTC by faergeek

2021-11-22 20:41 UTC, msmolyakov requested changes

2021-11-22 20:41 UTC, msmolyakov commented on README.md
> +- `16` - calls the function from a dApp script or account script
Only `from a dApp script`, not an account script.

2021-11-22 20:41 UTC, msmolyakov commented on README_ru.md
> +- `16` - вызывает функцию из dApp-скрипта или скрипта аккаунта
Только `из dApp-скрипта`. Обычные скрипты аккаунта нельзя вызывать через инвок.

2021-11-24 23:28 UTC, msmolyakov approved these changes

2021-11-25 09:20 UTC, smelnikov approved these changes

2021-11-25 09:38 UTC, merged