Add reverse migration flat state
wavesplatform/waves-keeper pull request #303
Opened 2022-05-25 16:32 UTC by ehassed3

2022-05-31 07:54 UTC, faergeek approved these changes
Actual reverse migration will be added in flat storage branch, right?

2022-05-31 07:54 UTC, faergeek commented on src/lib/localStore.ts
> +          await reverseMigrate.bind(this)();
I guess it can be replaced with just `.call` instead of `.bind`ing and then calling it:

```typescript
await reverseMigrate.call(this);
```

2022-05-31 07:54 UTC, faergeek commented on src/lib/localStore.ts
> +  public isSupported: boolean;
May be remove this flag already? Keeper can't work without `storage.local`. It would be just useless without it :-)

2022-06-01 05:03 UTC, smelnikov requested changes

2022-06-01 05:03 UTC, smelnikov commented on src/lib/localStore.ts
> +    if (version > CURRENT_MIGRATION_VERSION) {
I think we need some fallback mechanism in case one of the `reverseMigrate` fails.

2022-06-02 05:38 UTC, smelnikov approved these changes

2022-06-03 08:12 UTC, merged